print("hello, max. it's actually max")
require('max.remap')
require('max.options')
require('max.autocmds')
require('max.finder')
require('max.capture')
require('max.zettelkasten')
require('max.aguila')
